// Pricing tiers for PropScope
export const PLANS = [
  {
    id: 'deal-check',
    name: 'Deal Check',
    price: 97,
    cadence: 'per report',
    tagline: 'A fast go/no-go snapshot on any address.',
    cta: 'Run a Deal Check',
    highlight: false,
    features: [
      'Property & comps snapshot',
      'Estimated ARV and rent',
      'Quick MAO (max allowable offer)',
      '1-page summary PDF',
      'Email delivery in minutes',
    ],
    notIncluded: ['Full investment report', 'BRRRR analysis', 'Executive memo'],
  },
  {
    id: 'deal-analyzer',
    name: 'Deal Analyzer',
    price: 297,
    cadence: 'per report',
    tagline: 'The full investment report for a single deal.',
    cta: 'Get the full report',
    highlight: true,
    features: [
      'Everything in Deal Check',
      'Full fix-and-flip model',
      'Buy-and-hold cash flow & cap rate',
      'Rehab budget estimator',
      'Comparable sales analysis',
      'Sensitivity & risk scoring',
      'Multi-page investor-grade PDF',
    ],
    notIncluded: ['BRRRR analysis', 'Executive memo'],
  },
  {
    id: 'deal-intelligence',
    name: 'Deal Intelligence',
    price: 597,
    cadence: 'per report',
    tagline: 'Everything, plus BRRRR and an executive memo.',
    cta: 'Get Deal Intelligence',
    highlight: false,
    features: [
      'Everything in Deal Analyzer',
      'Full BRRRR strategy model',
      'Refinance & equity recapture',
      'Executive memo for partners/lenders',
      'Exit strategy comparison',
      'Neighborhood & market trend brief',
    ],
    notIncluded: [],
  },
  {
    id: 'investor-pro',
    name: 'Investor Pro',
    price: 497,
    cadence: 'per month',
    tagline: 'Unlimited reports for active investors & teams.',
    cta: 'Start Investor Pro',
    highlight: false,
    subscription: true,
    features: [
      'Unlimited Deal Intelligence reports',
      'Portfolio dashboard',
      'Saved buy-box & auto-scoring',
      'Team seats (up to 5)',
      'Priority report generation',
      'CSV / bulk address import',
    ],
    notIncluded: [],
  },
]

export const planById = (id) => PLANS.find((p) => p.id === id)
