import { Section } from '../../components/ui/Section.jsx'

const EFFECTIVE = 'July 30, 2026'

export default function Terms() {
  return (
    <Section className="pt-14">
      <div className="mx-auto max-w-3xl">
        <p className="eyebrow mb-3">Legal</p>
        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-3 text-sm text-ink-400">Last updated: {EFFECTIVE}</p>

        <div className="mt-8 space-y-2">
          <P>These Terms of Service ("Terms") govern your access to and use of PropScope (the "Service"),
            operated by [Your Legal Entity] ("PropScope," "we," "us"). By creating an account or using the
            Service, you agree to these Terms. If you do not agree, do not use the Service.</P>

          <H>1. The Service</H>
          <P>PropScope provides automated, software-generated real estate investment analysis — including
            estimated property values, rehab budgets, rents, comparable sales, and investment metrics — based
            on the information you provide and third-party data sources. Outputs are estimates generated by
            software and artificial intelligence.</P>

          <H>2. Not financial, investment, or professional advice</H>
          <P>PropScope is an informational tool. It is <b>not</b> a licensed broker, appraiser, lender, financial
            advisor, or tax or legal professional, and nothing in the Service constitutes financial, investment,
            appraisal, legal, tax, or other professional advice. All figures — including ARV, rehab estimates,
            rents, comparables, scores, and "max allowable offer" — are estimates that may be inaccurate or
            incomplete. You are solely responsible for independently verifying all information and for your own
            investment decisions. Do not rely on the Service as the sole basis for any purchase, sale, or
            financing decision.</P>

          <H>3. Accounts</H>
          <P>You must provide accurate information and keep your login credentials secure. You are responsible for
            all activity under your account. You must be at least 18 years old to use the Service.</P>

          <H>4. Plans, payments, and refunds</H>
          <P>The Service offers per-report purchases and a recurring "Investor Pro" subscription. Payments are
            processed by Stripe; by purchasing, you authorize the applicable charge. Subscriptions renew
            automatically each period until canceled, and you can cancel or manage your subscription at any time
            through the billing portal. Because reports are generated and delivered digitally on demand,
            <b> per-report purchases are non-refundable once the report has been generated</b>, except where
            required by law. Prices may change on a going-forward basis.</P>

          <H>5. Acceptable use</H>
          <P>You agree not to misuse the Service, including: reselling or redistributing reports or data except as
            permitted; scraping, reverse-engineering, or overloading the Service; violating any law or third-party
            right; or using the Service to build a competing dataset or product. We may suspend or terminate
            accounts that violate these Terms.</P>

          <H>6. Intellectual property</H>
          <P>The Service, its software, and its branding are owned by PropScope and protected by law. We grant you
            a limited, non-exclusive, non-transferable license to use the Service and the reports you generate for
            your own real estate activities. Reports you generate about properties you are evaluating are yours to
            use for those purposes.</P>

          <H>7. Third-party data and services</H>
          <P>The Service relies on third-party providers (including data, AI, hosting, and payment providers). We do
            not guarantee the accuracy, availability, or completeness of third-party data, and we are not
            responsible for third-party services.</P>

          <H>8. Disclaimers</H>
          <P>The Service is provided "as is" and "as available," without warranties of any kind, express or implied,
            including merchantability, fitness for a particular purpose, and non-infringement. We do not warrant
            that the Service or any estimate will be accurate, error-free, or uninterrupted.</P>

          <H>9. Limitation of liability</H>
          <P>To the maximum extent permitted by law, PropScope and its affiliates will not be liable for any
            indirect, incidental, special, consequential, or punitive damages, or for any lost profits, lost
            opportunities, or investment losses arising from your use of the Service. Our total liability for any
            claim relating to the Service will not exceed the amount you paid us in the 12 months before the claim.</P>

          <H>10. Indemnification</H>
          <P>You agree to indemnify and hold PropScope harmless from claims and expenses arising out of your use of
            the Service or your violation of these Terms.</P>

          <H>11. Termination</H>
          <P>You may stop using the Service at any time. We may suspend or terminate access if you violate these
            Terms or for operational reasons. Provisions that by their nature should survive termination will
            survive.</P>

          <H>12. Changes to these Terms</H>
          <P>We may update these Terms from time to time. Material changes will be reflected by updating the "Last
            updated" date, and your continued use after changes constitutes acceptance.</P>

          <H>13. Governing law</H>
          <P>These Terms are governed by the laws of the State of [Your State], without regard to conflict-of-law
            rules. Disputes will be resolved in the courts located in [Your County/State].</P>

          <H>14. Contact</H>
          <P>Questions about these Terms? Contact us at [support@getpropscope.com].</P>
        </div>
      </div>
    </Section>
  )
}

function H({ children }) { return <h2 className="pt-6 text-xl font-bold text-ink-900">{children}</h2> }
function P({ children }) { return <p className="text-ink-600 leading-relaxed">{children}</p> }
